Repository Point72/csp, pull requests merged in 2024-04, with the labels that each got.

#167 Run docs lints on PRs that change docs, add new logo, clean up unofficial roadmap
  .github/workflows/build.yml
  .github/workflows/conda.yml
  .github/workflows/wiki-lint.yml
  .github/workflows/wiki-publish.yml
  docs/img/csp-dark.png
  docs/img/csp-light.png
  docs/wiki/Home.md
Labels: part: documentation

#152 websocket client adapter
  CMakeLists.txt
  NOTICE
  conda/dev-environment-unix.yml
  cpp/csp/adapters/CMakeLists.txt
  cpp/csp/adapters/websocket/CMakeLists.txt
  cpp/csp/adapters/websocket/ClientAdapterManager.cpp
  cpp/csp/adapters/websocket/ClientAdapterManager.h
  cpp/csp/adapters/websocket/ClientHeaderUpdateAdapter.cpp
  cpp/csp/adapters/websocket/ClientHeaderUpdateAdapter.h
  cpp/csp/adapters/websocket/ClientInputAdapter.cpp
  cpp/csp/adapters/websocket/ClientInputAdapter.h
  cpp/csp/adapters/websocket/ClientOutputAdapter.cpp
  cpp/csp/adapters/websocket/ClientOutputAdapter.h
  cpp/csp/adapters/websocket/WebsocketEndpoint.cpp
  cpp/csp/adapters/websocket/WebsocketEndpoint.h
  cpp/csp/python/adapters/CMakeLists.txt
  cpp/csp/python/adapters/websocketadapterimpl.cpp
  csp/adapters/websocket.py
  csp/adapters/websocket_types.py
  csp/impl/wiring/numba_node.py
  examples/3_using_adapters/websocket_client.py
  setup.py
  vcpkg.json
Labels: type: feature, adapter: new

#185 websockets-adapter revert check for input adapter
  cpp/csp/adapters/websocket/ClientAdapterManager.cpp
Labels: type: bug, adapter: websocket

#184 Use manylinux-2-28 image for wheel builds
  .github/workflows/build.yml
  Makefile
  pyproject.toml
Labels: part: build

#142 Documentation Restructure
  docs/wiki/0.-Introduction.md
  docs/wiki/5.-Adapters.md
  docs/wiki/6.-Dynamic-Graphs.md
  docs/wiki/9.-Caching.md
  docs/wiki/Home.md
  docs/wiki/_Footer.md
  docs/wiki/_Sidebar.md
  docs/wiki/api-references/Base-Adapters-API.md
  docs/wiki/api-references/Base-Nodes-API.md
  docs/wiki/api-references/Functional-Methods-API.md
  docs/wiki/api-references/Input-Output-Adapters-API.md
  docs/wiki/api-references/Math-and-Logic-Nodes-API.md
  docs/wiki/api-references/Random-Time-Series-Generators-API.md
  docs/wiki/api-references/Statistical-Nodes-API.md
  docs/wiki/api-references/csp.Struct-API.md
  docs/wiki/api-references/csp.dynamic-API.md
  docs/wiki/api-references/csp.profiler-API.md
  docs/wiki/concepts/Adapters.md
  docs/wiki/concepts/CSP-Graph.md
  docs/wiki/concepts/CSP-Node.md
  docs/wiki/concepts/Execution-Modes.md
  docs/wiki/concepts/Historical-Buffers.md
  docs/wiki/dev-guides/Build-CSP-from-Source.md
  docs/wiki/dev-guides/Contribute.md
  docs/wiki/dev-guides/GitHub-Conventions.md
  docs/wiki/dev-guides/Local-Development-Setup.md
  docs/wiki/dev-guides/Release-Process.md
  docs/wiki/dev-guides/Roadmap.md
  docs/wiki/get-started/First-Steps.md
  docs/wiki/get-started/Installation.md
  docs/wiki/how-tos/Add-Cycles-in-Graphs.md
  docs/wiki/how-tos/Create-Dynamic-Baskets.md
  docs/wiki/how-tos/Profile-CSP-Code.md
  docs/wiki/how-tos/Use-Statistical-Nodes.md
  docs/wiki/how-tos/Write-Historical-Input-Adapters.md
  docs/wiki/how-tos/Write-Output-Adapters.md
  docs/wiki/how-tos/Write-Realtime-Input-Adapters.md
  docs/wiki/references/Examples.md
  docs/wiki/references/Glossary.md
Labels: part: documentation, tag: needs squash

#174 Start organizing examples, increase test coverage of examples
  Makefile
  conda/dev-environment-unix.yml
  csp/tests/test_examples.py
  examples/01_basics/README.md
  examples/01_basics/e1_basic.py
  examples/01_basics/e2_ticking.py
  examples/01_basics/e3_show_graph.py
  examples/01_basics/e4_trade_pnl.py
  examples/02_intermediate/README.md
  examples/02_intermediate/e1_feedback.py
  examples/02_intermediate/e2_stats.py
  examples/02_intermediate/e3_numpy_stats.py
  examples/02_intermediate/e4_exprtk.py
  examples/03_using_adapters/kafka/README.md
  examples/03_using_adapters/kafka/e1_kafka.py
  examples/03_using_adapters/parquet/README.md
  examples/03_using_adapters/parquet/e1_parquet_writer.py
  examples/03_using_adapters/slack/README.me
  examples/03_using_adapters/websocket/README.md
  examples/03_using_adapters/websocket/e1_websocket_output.py
  examples/04_writing_adapters/README.md
  examples/04_writing_adapters/e1_generic_push_adapter.py
  examples/04_writing_adapters/e2_pullinput.py
  examples/04_writing_adapters/e3_adaptermanager_pullinput.py
  examples/04_writing_adapters/e4_pushinput.py
  examples/04_writing_adapters/e5_adaptermanager_pushinput.py
  examples/04_writing_adapters/e6_outputadapter.py
  examples/04_writing_adapters/e7_adaptermanager_inputoutput.py
  examples/05_cpp/1_cpp_node/CMakeLists.txt
  examples/05_cpp/1_cpp_node/README.md
  examples/05_cpp/1_cpp_node/piglatin.cpp
  examples/05_cpp/1_cpp_node/piglatin/__init__.py
  examples/05_cpp/1_cpp_node/piglatin/__main__.py
  examples/05_cpp/1_cpp_node/pyproject.toml
  examples/05_cpp/1_cpp_node/setup.py
  examples/05_cpp/2_cpp_node_with_struct/.gitignore
  examples/05_cpp/2_cpp_node_with_struct/CMakeLists.txt
  examples/05_cpp/2_cpp_node_with_struct/README.md
  examples/05_cpp/2_cpp_node_with_struct/mystruct/__init__.py
  examples/05_cpp/2_cpp_node_with_struct/mystruct/__main__.py
  examples/05_cpp/2_cpp_node_with_struct/mystruct/node.py
  examples/05_cpp/2_cpp_node_with_struct/mystruct/struct.py
  examples/05_cpp/2_cpp_node_with_struct/pyproject.toml
  examples/05_cpp/2_cpp_node_with_struct/setup.py
  examples/05_cpp/2_cpp_node_with_struct/struct.cpp
  examples/05_cpp/README.md
  examples/06_advanced/README.md
  examples/06_advanced/e1_dynamic.py
  examples/06_advanced/e2_pandas_extension.py
  examples/6_advanced/e_12_caching_example.py
  examples/98_just_for_fun/README.md
  examples/98_just_for_fun/e1_csp_nand_computer.py
  examples/99_developer_tools/README.md
  examples/99_developer_tools/e1_profiling.py
  examples/99_developer_tools/e_22_profiling.py
  examples/README.md
  pyproject.toml
Labels: part: documentation

#200 Move websocket example after merge
  examples/03_using_adapters/websocket/e1_websocket_client.py
  examples/03_using_adapters/websocket/e2_websocket_output.py
Labels: part: documentation
