Repository Point72/csp, pull requests merged in 2024-08, with the labels that each got.

#348 Document in detail how duplicate timestamps are handled
  docs/wiki/api-references/Base-Nodes-API.md
  docs/wiki/concepts/Common-Mistakes.md
  docs/wiki/concepts/Execution-Modes.md
Labels: part: documentation

#353 Update roadmap to remove windows completion
  docs/wiki/dev-guides/Roadmap.md
Labels: part: documentation

#337 Move slack adapter to separate package
  conda/dev-environment-unix.yml
  conda/dev-environment-win.yml
  csp/adapters/slack.py
  csp/tests/adapters/test_slack.py
  docs/wiki/api-references/Input-Output-Adapters-API.md
  pyproject.toml
Labels: tag: internal, adapter: slack

#338 Make Getting Started tutorials use non-finance examples and fix up various documentation issues
  docs/wiki/api-references/csp.profiler-API.md
  docs/wiki/concepts/CSP-Graph.md
  docs/wiki/concepts/CSP-Node.md
  docs/wiki/get-started/First-Steps.md
  docs/wiki/get-started/IO-with-Adapters.md
  docs/wiki/get-started/More-with-CSP.md
  docs/wiki/images/corr-graph.png
  docs/wiki/images/corr-trend.png
  docs/wiki/images/monitor-graph.png
Labels: part: documentation

#356 Clean up retail example and resolve conflicts with other docs PR
  docs/wiki/_Sidebar.md
  docs/wiki/get-started/Build-a-Basic-App.md
  examples/01_basics/README.md
  examples/01_basics/e5_retail_cart.py
  examples/README.md
Labels: part: documentation, tag: needs squash, part: examples
