Repository Point72/csp, pull requests merged in 2024-06, with the labels that each got.

#249 Update release instructions
  docs/wiki/dev-guides/Local-Development-Setup.md
  docs/wiki/dev-guides/Release-Process.md
Labels: part: documentation, tag: internal, tag: needs squash

#266 Make tag info a more prominent note
  docs/wiki/dev-guides/Release-Process.md
Labels: part: documentation, tag: internal

#246 First cut of seismic waveform example
  examples/07_end_to_end/README.md
  examples/07_end_to_end/seismic_waveform.ipynb
Labels: part: documentation

#197 Add notebook with NYC MTA example
  docs/wiki/references/Examples.md
  examples/07_end_to_end/README.md
  examples/07_end_to_end/mta.ipynb
  examples/07_end_to_end/seismic_waveform.ipynb
Labels: part: documentation, type: enhancement

#260 Getting started tutorials/guides
  docs/wiki/Home.md
  docs/wiki/_Sidebar.md
  docs/wiki/get-started/First-Steps.md
  docs/wiki/get-started/IO-with-Adapters.md
  docs/wiki/get-started/Installation.md
  docs/wiki/get-started/More-with-CSP.md
  docs/wiki/images/ask-bid-graph.png
  docs/wiki/images/pnl-graph.png
  examples/03_using_adapters/parquet/e1_parquet_write_read.py
Labels: part: documentation, tag: needs squash

#225 Add realtime/historical adapter example with wikimedia data
  examples/07_end_to_end/README.md
  examples/07_end_to_end/wikimedia.ipynb
Labels: part: documentation, tag: needs squash

#275 Fix some broken links in examples, typos/misformatting in wiki
  README.md
  docs/wiki/api-references/Base-Nodes-API.md
  docs/wiki/concepts/Historical-Buffers.md
  docs/wiki/get-started/First-Steps.md
  docs/wiki/get-started/IO-with-Adapters.md
  docs/wiki/how-tos/Write-Historical-Input-Adapters.md
  docs/wiki/how-tos/Write-Output-Adapters.md
  docs/wiki/how-tos/Write-Realtime-Input-Adapters.md
  examples/03_using_adapters/parquet/README.md
  examples/03_using_adapters/slack/README.md
  examples/03_using_adapters/websocket/README.md
  examples/05_cpp/README.md
  examples/06_advanced/README.md
  examples/07_end_to_end/mta.ipynb
  examples/README.md
Labels: part: documentation

#276 Remove note about lack of windows support on conda, tweak some language in docs
  docs/wiki/get-started/First-Steps.md
  docs/wiki/get-started/Installation.md
  examples/01_basics/e2_ticking.py
Labels: part: documentation, tag: needs squash

#283 Remove note about gnu toolchain from docs
  docs/wiki/dev-guides/Build-CSP-from-Source.md
Labels: part: documentation

#284 Force numpy<2 for now
  conda/dev-environment-unix.yml
  conda/dev-environment-win.yml
  pyproject.toml
Labels: part: dependencies, part: build

#281 Fix two bugs in unadjusted, tick-based EMA when NaNs are present
  cpp/csp/cppnodes/statsimpl.h
  csp/tests/test_stats.py
Labels: type: bug, lang: c++
