Repository Point72/csp, pull requests merged in 2024-07, with the labels that each got.

#310 tiny fix to README
  README.md
Labels: part: documentation

#280 Add postprocess_to_dict hook for to_dict method in structs
  cpp/csp/python/PyStructToDict.cpp
  csp/impl/struct.py
  csp/tests/impl/test_struct.py
Labels: type: enhancement

#320 Clean up warnings from CSP code during build
  CMakeLists.txt
  cpp/csp/adapters/parquet/ParquetOutputAdapter.cpp
  cpp/csp/engine/Struct.h
  cpp/csp/python/PyStructFastList_impl.h
  cpp/csp/python/PyStructList_impl.h
  cpp/csp/python/PyStructToJson.cpp
  cpp/csp/python/adapters/CMakeLists.txt
  cpp/tests/CMakeLists.txt
Labels: type: enhancement

#327 Deprecate defineStruct and defineNestedStruct in favor of define_struct and define_nested_struct
  conda/dev-environment-unix.yml
  conda/dev-environment-win.yml
  csp/adapters/db.py
  csp/build/csp_autogen.py
  csp/impl/pandas_accessor.py
  csp/impl/struct.py
  csp/tests/impl/test_struct.py
  csp/tests/test_baselib.py
  pyproject.toml
Labels: type: enhancement

#333 Improve implementation of statistics functions Quantile/Rank using `boost::multi_index`
  cpp/csp/cppnodes/statsimpl.h
  vcpkg.json
Labels: type: enhancement, lang: c++

#321 Add support for additional python types as dict keys in Struct.to_json
  cpp/csp/python/PyStructToJson.cpp
  csp/tests/impl/test_struct.py
  docs/wiki/api-references/csp.Struct-API.md
Labels: type: enhancement

#344 Fix maintainer instructions for checking out PRs
  docs/wiki/dev-guides/GitHub-Conventions.md
  docs/wiki/dev-guides/Release-Process.md
Labels: part: documentation, tag: internal

#345 Fix up earthquake data push-pull adapter example
  examples/07_end_to_end/README.md
  examples/07_end_to_end/earthquake.ipynb
Labels: part: examples

#346 Fix up examples documentation and add the earthquake example
  docs/wiki/Home.md
  docs/wiki/_Sidebar.md
  docs/wiki/images/earthquake-example.png
  docs/wiki/images/mta-example.png
  docs/wiki/images/seismic-waveform-example.png
  docs/wiki/images/wikimedia-example.png
  docs/wiki/references/Examples.md
  examples/01_basics/README.md
  examples/03_using_adapters/websocket/README.md
  examples/README.md
Labels: part: documentation, part: examples

#342 Improve `csp.feedback` documentation with better example and document `DelayedEdge`
  docs/wiki/_Sidebar.md
  docs/wiki/concepts/Feedback-and-Delayed-Edge.md
  docs/wiki/how-tos/Add-Cycles-in-Graphs.md
  docs/wiki/images/feedback-graph.png
Labels: part: documentation

#343 Document `csp.run`, `csp.run_on_thread` and `csp.show_graph`
  docs/wiki/_Sidebar.md
  docs/wiki/api-references/Graph-Utilities-API.md
Labels: part: documentation

#335 Fix struct __dir__ implementation
  csp/impl/struct.py
  csp/tests/impl/test_struct.py
Labels: type: bug

#334 Add signature to adapters so that help works as expected
  csp/impl/wiring/adapters.py
  csp/impl/wiring/signature.py
  csp/tests/impl/test_outputadapter.py
  csp/tests/impl/test_pushadapter.py
Labels: type: enhancement

#312 expose engine shutdown to adapter manager and push/pushpull adapters
  cpp/csp/python/Exception.h
  cpp/csp/python/PyAdapterManager.cpp
  cpp/csp/python/PyEngine.h
  cpp/csp/python/PyPushInputAdapter.cpp
  cpp/csp/python/PyPushPullInputAdapter.cpp
  csp/tests/impl/test_pushadapter.py
  csp/tests/impl/test_pushpulladapter.py
  csp/tests/test_engine.py
  docs/wiki/how-tos/Write-Realtime-Input-Adapters.md
Labels: type: enhancement, tag: needs squash

#341 Use hidden visibility for symbols for non-windows platforms
  CMakeLists.txt
  Makefile
  cpp/csp/adapters/kafka/KafkaAdapterManager.h
  cpp/csp/adapters/parquet/DialectGenericListReaderInterface.h
  cpp/csp/adapters/parquet/ParquetInputAdapterManager.h
  cpp/csp/adapters/parquet/ParquetOutputAdapterManager.h
  cpp/csp/adapters/parquet/ParquetReaderColumnAdapter.cpp
  cpp/csp/adapters/websocket/ClientAdapterManager.h
  cpp/csp/core/Exception.h
  cpp/csp/core/Platform.h
  cpp/csp/engine/AdapterManager.h
  cpp/csp/engine/Feedback.h
  cpp/csp/engine/Struct.h
  cpp/csp/python/Exception.h
  cpp/csp/python/InitHelper.h
  cpp/csp/python/PyCspEnum.h
  cpp/csp/python/adapters/CMakeLists.txt
Labels: type: enhancement, lang: c++
