Repository Point72/csp, pull requests merged in 2024-12, with the labels that each got.

#410 Fix perspective test for win32 build
  csp/tests/impl/test_pandas_perspective.py
Labels: type: bug

#409 Remove unused object_factory_registry. Fixes #377
  csp/impl/wiring/signature.py
  csp/tests/utils/test_object_factory.py
  csp/utils/classproperty.py
  csp/utils/object_factory_registry.py
  csp/utils/qualified_name_utils.py
  csp/utils/rm_utils.py
Labels: type: enhancement

#408 Support Literal and Union/Optional types on structs. Fixes #405
  csp/impl/struct.py
  csp/impl/types/container_type_normalizer.py
  csp/tests/impl/test_struct.py
Labels: type: bug

#413 Add automatic full CI builds that run twice a week
  .github/workflows/build.yml
Labels: part: github_actions

#415 Pin cmake on Windows builds to 3.31.1 as the new patch release is failing to install on GitHub Actions
  Makefile
Labels: part: build
