Repository Point72/csp, pull requests merged in 2024-03, with the labels that each got.

#124 Move to ruff check
  Makefile
  csp/build/csp_autogen.py
  csp/impl/adaptermanager.py
  csp/impl/wiring/numba_node.py
  csp/impl/wiring/numba_utils/csp_numba_functions.py
  csp/tests/impl/test_struct.py
  csp/tests/test_stats.py
  examples/2_intermediate/e_18_pandas_extension_example.py
  examples/4_writing_adapters/e_14_generic_push_adapter.py
  examples/4_writing_adapters/e_14_user_adapters_04_adaptermanager_pushinput.py
  examples/98_just_for_fun/e_99_csp_nand_computer.py
  pyproject.toml
Labels: tag: internal, build

#128 Add developer guide and move build instructions to their own page
  docs/wiki/98.-Building-From-Source.md
  docs/wiki/99.-Developer.md
  docs/wiki/Home.md
Labels: documentation

#136 Lint and format docs
  Makefile
  README.md
  dev-environment.yml
  docs/wiki/0.-Introduction.md
  docs/wiki/1.-Generic-Nodes-(csp.baselib).md
  docs/wiki/2.-Math-Nodes-(csp.math).md
  docs/wiki/3.-Statistics-Nodes-(csp.stats).md
  docs/wiki/4.-Random-Time-Series-Generation-(csp.random).md
  docs/wiki/5.-Adapters.md
  docs/wiki/6.-Dynamic-Graphs.md
  docs/wiki/7.-csp.Struct.md
  docs/wiki/8.-Profiler.md
  docs/wiki/9.-Caching.md
  docs/wiki/98.-Building-From-Source.md
  docs/wiki/99.-Developer.md
  docs/wiki/Home.md
  examples/README.md
  pyproject.toml
Labels: documentation

#134 Struct deepcopy implementation
  cpp/csp/engine/CspType.h
  cpp/csp/engine/DialectGenericType.h
  cpp/csp/engine/Struct.cpp
  cpp/csp/engine/Struct.h
  cpp/csp/python/PyCspType.cpp
  cpp/csp/python/PyStruct.cpp
  csp/tests/impl/test_struct.py
Labels: enhancement

#157 Skip conda e2e tests for docs-only builds to match main build workflow
  .github/workflows/conda.yml
Labels: tag: internal, build

#146 skip sdist tests except on full runs
  .github/workflows/build.yml
Labels: tag: internal, build

#151 fix copypasta in pyproject.toml
  pyproject.toml
Labels: bug, tag: internal

#161 Run autofixer
  csp/tests/impl/test_struct.py
Labels: tag: internal

#160 Add ssl passthrough for slack adapter
  csp/adapters/slack.py
  csp/tests/adapters/test_slack.py
Labels: adapter: slack

#162 Tweaks to CMake passthrough, small fixes in prep for mac and windows
  .github/CODEOWNERS
  CMakeLists.txt
  cpp/cmake/modules/FindCSP.cmake
  cpp/cmake/modules/Findcsp_autogen.cmake
  cpp/csp/engine/Scheduler.h
  cpp/tests/core/CMakeLists.txt
  setup.py
Labels: build

#163 Re-enable C++ testing
  Makefile
  conda/dev-environment-linux.yml
  cpp/tests/core/CMakeLists.txt
  cpp/tests/engine/CMakeLists.txt
  setup.py
Labels: tests, lang: c++, tag: needs squash

#164 Fix bug where a node can be stopped when it hasn't started
  cpp/cmake/modules/FindCSP.cmake
  cpp/csp/engine/AdapterManager.cpp
  cpp/csp/engine/AdapterManager.h
  cpp/csp/engine/Consumer.cpp
  cpp/csp/engine/Consumer.h
  cpp/csp/engine/Engine.cpp
  cpp/csp/engine/InputAdapter.cpp
  cpp/csp/engine/InputAdapter.h
  cpp/csp/python/CMakeLists.txt
  cpp/csp/python/csptestlibimpl.cpp
  csp/impl/wiring/node_parser.py
  csp/tests/test_engine.py
Labels: bug

#132 Clang build support
  .github/workflows/build.yml
  .github/workflows/conda.yml
  CMakeLists.txt
  Makefile
  conda/dev-environment-unix.yml
  cpp/csp/adapters/parquet/ArrowSingleColumnArrayBuilder.h
  cpp/csp/adapters/parquet/ParquetOutputAdapter.h
  cpp/csp/adapters/parquet/ParquetReader.h
  cpp/csp/adapters/parquet/ParquetReaderColumnAdapter.h
  cpp/csp/adapters/utils/JSONMessageWriter.h
  cpp/csp/adapters/utils/MessageStructConverter.h
  cpp/csp/core/QueueWaiter.h
  cpp/csp/cppnodes/statsimpl.h
  cpp/csp/engine/ConstInputAdapter.h
  cpp/csp/engine/CppNode.h
  cpp/csp/engine/CspType.h
  cpp/csp/engine/DialectGenericType.h
  cpp/csp/engine/DynamicEngine.h
  cpp/csp/engine/Feedback.h
  cpp/csp/engine/PendingPushEvents.h
  cpp/csp/engine/RootEngine.cpp
  cpp/csp/engine/RootEngine.h
  cpp/csp/engine/Struct.h
  cpp/csp/engine/VectorContainer.cpp
  cpp/csp/python/InitHelper.h
  cpp/csp/python/PyCspType.h
  cpp/csp/python/adapters/parquetadapterimpl.cpp
  cpp/csp/python/cspbaselibimpl.cpp
  cpp/csp/python/cspimpl.cpp
  cpp/tests/core/test_time.cpp
  csp/adapters/parquet.py
  csp/tests/adapters/test_parquet.py
  csp/tests/test_engine.py
  docs/wiki/98.-Building-From-Source.md
  setup.py
Labels: build
