Repository Point72/csp, pull requests merged in 2024-05, with the labels that each got.

#220 minor bugfix to unroll cppimpl
  cpp/csp/cppnodes/baselibimpl.cpp
Labels: type: bug, lang: c++

#219 Fix JSONTextMessageMapper Bug in WebsocketAdapterManager
  cpp/csp/adapters/websocket/ClientInputAdapter.cpp
  cpp/csp/adapters/websocket/ClientInputAdapter.h
  cpp/csp/adapters/websocket/ClientOutputAdapter.h
  csp/tests/adapters/test_websocket.py
Labels: type: bug, adapter: websocket

#213 Remove all caching code from CSP
  csp/__init__.py
  csp/baselib.py
  csp/cache_support.py
  csp/impl/config.py
  csp/impl/managed_dataset/__init__.py
  csp/impl/managed_dataset/aggregation_period_utils.py
  csp/impl/managed_dataset/cache_partition_argument_serializer.py
  csp/impl/managed_dataset/cache_user_custom_object_serializer.py
  csp/impl/managed_dataset/dataset_metadata.py
  csp/impl/managed_dataset/dateset_name_constants.py
  csp/impl/managed_dataset/datetime_utils.py
  csp/impl/managed_dataset/managed_dataset.py
  csp/impl/managed_dataset/managed_dataset_lock_file_util.py
  csp/impl/managed_dataset/managed_dataset_merge_utils.py
  csp/impl/managed_dataset/managed_dataset_path_resolver.py
  csp/impl/managed_dataset/managed_parquet_writer.py
  csp/impl/mem_cache.py
  csp/impl/types/instantiation_type_resolver.py
  csp/impl/wiring/base_parser.py
  csp/impl/wiring/cache_support/__init__.py
  csp/impl/wiring/cache_support/cache_config_resolver.py
  csp/impl/wiring/cache_support/cache_type_mapper.py
  csp/impl/wiring/cache_support/dataset_partition_cached_data.py
  csp/impl/wiring/cache_support/graph_building.py
  csp/impl/wiring/cache_support/partition_files_container.py
  csp/impl/wiring/cache_support/runtime_cache_manager.py
  csp/impl/wiring/context.py
  csp/impl/wiring/graph.py
  csp/impl/wiring/graph_parser.py
  csp/impl/wiring/node.py
  csp/impl/wiring/node_parser.py
  csp/impl/wiring/outputs.py
  csp/impl/wiring/runtime.py
  csp/impl/wiring/signature.py
  csp/impl/wiring/special_output_names.py
  csp/impl/wiring/threaded_runtime.py
  csp/tests/impl/test_struct.py
  csp/tests/test_caching.py
  csp/tests/test_engine.py
  csp/tests/test_parsing.py
Labels: type: feature

#223 Pin linters to avoid noise, run auto fixers after latest changes and pinning
  conda/dev-environment-unix.yml
  docs/wiki/concepts/Execution-Modes.md
  docs/wiki/dev-guides/Build-CSP-from-Source.md
  pyproject.toml
  setup.py
Labels: tag: internal

#226 rename name in conda dev env yml from csp-dev to csp to match env in setup wiki
  .github/CODEOWNERS
  conda/dev-environment-unix.yml
Labels: tag: internal

#238 Add better minimap directors
  .github/workflows/build.yml
Labels: tag: internal

#250 Sign commit when using bump version
  .bumpversion.cfg
  Makefile
Labels: tag: internal

#248 Move websocket backend to boost::beast
  NOTICE
  conda/dev-environment-unix.yml
  conda/dev-environment-win.yml
  cpp/csp/adapters/websocket/CMakeLists.txt
  cpp/csp/adapters/websocket/ClientAdapterManager.cpp
  cpp/csp/adapters/websocket/ClientAdapterManager.h
  cpp/csp/adapters/websocket/ClientHeaderUpdateAdapter.h
  cpp/csp/adapters/websocket/ClientInputAdapter.cpp
  cpp/csp/adapters/websocket/ClientInputAdapter.h
  cpp/csp/adapters/websocket/ClientOutputAdapter.cpp
  cpp/csp/adapters/websocket/ClientOutputAdapter.h
  cpp/csp/adapters/websocket/WebsocketEndpoint.cpp
  cpp/csp/adapters/websocket/WebsocketEndpoint.h
  csp/adapters/websocket.py
  csp/tests/adapters/test_websocket.py
  setup.py
  vcpkg.json
Labels: lang: c++, adapter: websocket

#258 Remove unused LockFile and FilePermissions classes from old caching code
  csp/impl/struct.py
  csp/tests/impl/utils/__init__.py
  csp/tests/impl/utils/test_lock_file.py
  csp/utils/file_permissions.py
  csp/utils/lock_file.py
Labels: type: enhancement, lang: python

#262 Fix string interpolation for cache flag in CI
  .github/actions/setup-caches/action.yml
Labels: type: bug, tag: internal, part: build
