Repository Point72/csp, pull requests merged in 2024-02, with the labels that each got.

#29 Fixes for examples
  csp/__init__.py
  dev-environment.yml
  pyproject.toml
Labels: documentation

#27 Clean up metadata and email references
  .github/CODE_OF_CONDUCT.md
  csp/examples/e_23_cpp_example/pyproject.toml
  csp/examples/e_24_cpp_struct_example/pyproject.toml
  pyproject.toml
Labels: tag: internal

#6 Support sqlalchemy>=2
  .github/workflows/build.yml
  Makefile
  csp/adapters/db.py
  csp/adapters/output_adapters/parquet.py
  csp/adapters/parquet.py
  csp/tests/adapters/test_db.py
  dev-environment.yml
  pyproject.toml
Labels: enhancement, lang: python

#30 Skip graphviz tests if not installed locally
  csp/tests/test_showgraph.py
Labels: tests, tag: internal

#36 Show result of first example in readme
  README.md
Labels: documentation

#37 Drop macos-12 (x86) build in frequent CI
  .github/workflows/build.yml
Labels: github_actions, tag: internal

#41 Add function names to type resolver errors and properly report when the return value is the conflicting type
  csp/impl/types/instantiation_type_resolver.py
  csp/tests/test_caching.py
  csp/tests/test_engine.py
  csp/tests/test_type_checking.py
Labels: tag: internal

#47 remove symlink in example which causes recursive copying of tree in sdist
  csp/examples/e_23_cpp_example/csp
Labels: tag: internal, distribution

#50 Add channel selection to dev-environment.yml file
  dev-environment.yml
Labels: tag: internal, build

#45 Add notice for licenses of dependencies
  .github/workflows/build.yml
  MANIFEST.in
  Makefile
  NOTICE
Labels: tag: internal, distribution

#53 Add dependency for python 3.8, reenable sdist
  .github/workflows/build.yml
  CMakeLists.txt
  csp/tests/test_profiler.py
  pyproject.toml
  setup.py
Labels: github_actions, tag: internal, build

#56 Adding poisson_timer and brownian_motion to new csp.random module
  csp/random.py
  csp/tests/test_random.py
  pyproject.toml
Labels: feature

#76 Add attribution block to readme
  README.md
Labels: documentation, tag: internal

#78 csp.stats.list_to_numpy should return a 1DArray, not an NDArray
  csp/stats.py
  csp/tests/test_stats.py
Labels: bug, lang: python

#75 Remove GNU PBDS dependence in stats classes and improve ArgMinMax implementation
  cpp/csp/cppnodes/statsimpl.h
Labels: enhancement, lang: c++

#26 Refactor and test examples
  .gitignore
  MANIFEST.in
  Makefile
  csp/examples/e_03_numba_simple_example.py
  csp/examples/e_24_cpp_struct_example/mystruct/__init__.py
  csp/tests/test_engine.py
  csp/tests/test_examples.py
  examples/1_basics/e_01_trade_pnl.py
  examples/1_basics/e_02_show_graph.py
  examples/2_intermediate/e_13_feedback.py
  examples/2_intermediate/e_15_dynamic.py
  examples/2_intermediate/e_19_exprtk_example.py
  examples/2_intermediate/e_20_stats.py
  examples/2_intermediate/e_21_numpy_stats.py
  examples/3_using_adapters/e_06_parquet_writer_example.py
  examples/3_using_adapters/e_08_kafka.py
  examples/3_using_adapters/e_11_websocket_output.py
  examples/4_writing_adapters/e_14_generic_push_adapter.py
  examples/4_writing_adapters/e_14_user_adapters_01_pullinput.py
  examples/4_writing_adapters/e_14_user_adapters_02_adaptermanager_siminput.py
  examples/4_writing_adapters/e_14_user_adapters_03_pushinput.py
  examples/4_writing_adapters/e_14_user_adapters_04_adaptermanager_pushinput.py
  examples/4_writing_adapters/e_14_user_adapters_05_outputadapter.py
  examples/4_writing_adapters/e_14_user_adapters_06_adaptermanager_inputoutput.py
  examples/5_cpp/1_cpp_node/CMakeLists.txt
  examples/5_cpp/1_cpp_node/README.md
  examples/5_cpp/1_cpp_node/piglatin.cpp
  examples/5_cpp/1_cpp_node/piglatin/__init__.py
  examples/5_cpp/1_cpp_node/piglatin/__main__.py
  examples/5_cpp/1_cpp_node/pyproject.toml
  examples/5_cpp/1_cpp_node/setup.py
  examples/5_cpp/2_cpp_node_with_struct/.gitignore
  examples/5_cpp/2_cpp_node_with_struct/CMakeLists.txt
  examples/5_cpp/2_cpp_node_with_struct/README.md
  examples/5_cpp/2_cpp_node_with_struct/mystruct/__init__.py
  examples/5_cpp/2_cpp_node_with_struct/mystruct/__main__.py
  examples/5_cpp/2_cpp_node_with_struct/mystruct/node.py
  examples/5_cpp/2_cpp_node_with_struct/mystruct/struct.py
  examples/5_cpp/2_cpp_node_with_struct/pyproject.toml
  examples/5_cpp/2_cpp_node_with_struct/setup.py
  examples/5_cpp/2_cpp_node_with_struct/struct.cpp
  examples/6_advanced/e_12_caching_example.py
  examples/98_just_for_fun/e_99_csp_nand_computer.py
  examples/99_developer_tools/e_22_profiling.py
  examples/README.md
Labels: documentation

#54 Add a workflow job to automate uploading to testpypi
  .github/workflows/build.yml
Labels: tag: internal, distribution

#92 Fix failing websocket adapter example
  examples/3_using_adapters/e_11_websocket_output.py
Labels: bug

#90 Upload release artifacts to github releases
  .github/workflows/build.yml
Labels: distribution

#95 Skip examples tests if the folder isnt present (on installation) or via manual override
  .github/workflows/build.yml
  csp/tests/test_examples.py
Labels: bug, tag: internal

#93 Fix type annotation for `csp.apply`
  csp/baselib.py
Labels: enhancement, tag: wip, tag: internal

#97 Add missing runtime dependencies, fixes #96
  pyproject.toml
Labels: bug, tag: internal

#100 scope publish section only when releasing, remove permissions section
  .github/workflows/build.yml
Labels: tag: internal, build

#101 Readd id-token permission for pypi
  .github/workflows/build.yml
Labels: github_actions, tag: internal, build

#104 Compare floats by epsilon in `drop_dupes_float`
  cpp/csp/cppnodes/baselibimpl.cpp
  cpp/csp/python/cspbaselibimpl.cpp
  csp/baselib.py
  csp/tests/test_baselib.py
Labels: enhancement

#103 Check wheels and sdist for issues with twine check
  .github/actions/setup-python/action.yml
  .github/workflows/build.yml
  Makefile
Labels: tag: internal, build

#107 Build sdist with build to ensure proper readme contents and format
  Makefile
  pyproject.toml
  setup.py
Labels: tag: internal, build

#108 use `twine check --strict` in dist-check
  Makefile
Labels: tag: internal, distribution

#110 Add example for the pandas extension types
  csp/impl/wiring/edge.py
  examples/2_intermediate/e_18_pandas_extension_example.py
Labels: documentation, enhancement

#87 Symphony adapter
  csp/adapters/symphony.py
  csp/tests/adapters/test_symphony.py
  pyproject.toml
Labels: feature, adapter: new

#22 Add slack message adapter
  csp/adapters/slack.py
  csp/tests/adapters/test_slack.py
  pyproject.toml
Labels: feature, adapter: new

#120 Fix typo in pyproject.toml for python versions link
  README.md
Labels: bug, tag: internal
