Repository Point72/csp, pull requests merged in 2025-06, with the labels that each got.

#543 Release v0.10.1
  CMakeLists.txt
  csp/__init__.py
  pyproject.toml
  setup.py
Labels: part: distribution

#548 Document the csp.basketlib library
  docs/wiki/_Sidebar.md
  docs/wiki/api-references/Basket-Nodes-API.md
Labels: part: documentation

#547 Add allow_non_overlapping parameter for bivariate statistics
  Makefile
  cpp/csp/cppnodes/statsimpl.cpp
  cpp/csp/python/cspstatsimpl.cpp
  csp/stats.py
  csp/tests/test_stats.py
  docs/wiki/api-references/Statistical-Nodes-API.md
Labels: type: enhancement

#550 Fix NaN handling bug in adjusted, unbiased ema_cov with a finite horizon and ignore_na=True
  cpp/csp/cppnodes/statsimpl.h
  csp/tests/test_stats.py
Labels: type: bug

#541 Add record batch adapter to zero-copy stream record batches into csp
  CMakeLists.txt
  cpp/cmake/modules/FindDepsArrowAdapter.cmake
  cpp/csp/python/CMakeLists.txt
  cpp/csp/python/adapters/ArrowInputAdapter.h
  cpp/csp/python/adapters/CMakeLists.txt
  cpp/csp/python/adapters/PyArrowInputAdapter.cpp
  csp/adapters/arrow.py
  csp/tests/adapters/test_arrow.py
  setup.py
Labels: type: feature, adapter: new

#537 Update roadmap for current state
  docs/wiki/dev-guides/Roadmap.md
Labels: part: documentation
