Repository Point72/csp, pull requests merged in 2025-08, with the labels that each got.

#525 Replace deprecated ast module classes, fixes #524
  csp/impl/types/type_annotation_normalizer_transformer.py
  csp/impl/wiring/base_parser.py
  csp/impl/wiring/node_parser.py
  csp/impl/wiring/numba_node_parser.py
Labels: type: enhancement, tag: internal

#570 Add support for unadjusted halflife-based EMA calculations
  cpp/csp/cppnodes/statsimpl.cpp
  cpp/csp/cppnodes/statsimpl.h
  cpp/csp/python/cspnpstatsimpl.cpp
  cpp/csp/python/cspstatsimpl.cpp
  cpp/csp/python/npstatsimpl.cpp
  csp/stats.py
  csp/tests/test_stats.py
  docs/wiki/api-references/Statistical-Nodes-API.md
Labels: type: enhancement, type: feature

#576 Fix csp.stats for NumPy scalar arrays which have 0-dimensions
  cpp/csp/python/npstatsimpl.cpp
  csp/tests/test_stats.py
Labels: type: bug
