Repository Point72/csp, pull requests merged in 2025-03, with the labels that each got.

#461 Set appropriate lower bound for pyarrow, add missing required runtime dep on pydantic
  conda/dev-environment-unix.yml
  pyproject.toml
Labels: type: bug, part: dependencies

#471 Handle `Any` type properly in pydantic type checking. Fixes #468
  csp/impl/types/pydantic_types.py
  csp/impl/types/typing_utils.py
  csp/tests/impl/types/test_pydantic_type_resolver.py
  csp/tests/impl/types/test_tstype.py
Labels: lang: python

#478 Handle union and literal typing correctly in annotations
  csp/impl/struct.py
  csp/impl/types/container_type_normalizer.py
  csp/impl/types/pydantic_types.py
  csp/impl/types/type_annotation_normalizer_transformer.py
  csp/impl/types/typing_utils.py
  csp/tests/impl/test_struct.py
  csp/tests/impl/types/test_pydantic_types.py
  csp/tests/test_type_checking.py
Labels: type: bug

#479 Allow using pydantic for from_dict, schema for FastList
  csp/impl/struct.py
  csp/impl/types/typing_utils.py
  csp/tests/impl/test_struct.py
Labels: type: enhancement

#501 Add optional support for preserving enums in to_dict
  cpp/csp/python/PyStruct.cpp
  cpp/csp/python/PyStructToDict.cpp
  cpp/csp/python/PyStructToDict.h
  csp/impl/struct.py
  csp/tests/impl/test_struct.py
  docs/wiki/api-references/csp.Struct-API.md
Labels: type: enhancement

#509 Pin cmake to <4 as 4 is not compatible with external deps which allow <3.5
  Makefile
Labels: part: build

#506 Allow csp.Struct as a generic field member to be autogened. Fixes cr…
  cpp/csp/python/PyStruct.cpp
  csp/build/csp_autogen.py
  csp/tests/impl/test_struct.py
Labels: type: bug
