Repository Point72/csp, pull requests merged in 2025-01, with the labels that each got.

#423 Add zlib dependency to conda dev environment and update websocket code for boost 1.87
  conda/dev-environment-unix.yml
  conda/dev-environment-win.yml
  cpp/csp/adapters/websocket/WebsocketEndpoint.cpp
Labels: part: build

#424 Scheduled CI builds for CSP conda end-to-end tests
  .github/workflows/conda.yml
Labels: part: dependencies, part: build

#401 Add example notebook of live inference for pydata global 2024
  examples/07_end_to_end/wikimedia_inference.ipynb
Labels: part: documentation

#429 Pin pyarrow to <19 due to apparent incompatibility with vendored 16.0 Arrow C++ code on x86 macos
  conda/dev-environment-unix.yml
  conda/dev-environment-win.yml
  pyproject.toml
Labels: part: dependencies

#432 Release v0.0.7
  CMakeLists.txt
  csp/__init__.py
  pyproject.toml
  setup.py
Labels: tag: internal
